import type { Product } from '@/types/commerce';

export const catalog: Product[] = [
  {
    id: 'sku-1001',
    name: 'NeoLedger Pro',
    description: 'Accounting automation suite for SMB merchants who need reconciliation and tax-ready reports.',
    category: 'software',
    price: 5999,
    currency: 'INR',
    stock: 24,
    tags: ['accounting', 'automation', 'finance'],
    agentFriendly: true,
    bundleHints: ['invoice automation', 'cashflow insights'],
  },
  {
    id: 'sku-1002',
    name: 'SmartGST Vault',
    description: 'GST filing and advisory workflow for merchants with multi-state operations.',
    category: 'software',
    price: 2499,
    currency: 'INR',
    stock: 18,
    tags: ['gst', 'compliance'],
    agentFriendly: true,
    bundleHints: ['tax filing', 'compliance backup'],
  },
  {
    id: 'sku-2001',
    name: 'Velocity Shipping Kit',
    description: 'Inventory, fulfillment, and address validation bundle for e-commerce operations.',
    category: 'logistics',
    price: 3899,
    currency: 'INR',
    stock: 11,
    tags: ['fulfillment', 'shipping'],
    agentFriendly: true,
    bundleHints: ['warehouse tracking'],
  },
  {
    id: 'sku-3001',
    name: 'Loyalty Engine Plus',
    description: 'Retention automation engine to increase repeat purchases through personalized offers.',
    category: 'marketing',
    price: 3299,
    currency: 'INR',
    stock: 17,
    tags: ['loyalty', 'retention', 'marketing'],
    agentFriendly: true,
    bundleHints: ['retention campaigns', 'customer journeys'],
  },
];
